spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  cache:
    type: redis
    cache-names: coffee
    time-to-live: 5s
    cache-null-values: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6370

mybatis:
  mapper-locations: classpath:mapper/xml/*.xml
  type-aliases-package: geektime.spring.springbucks.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    geektime.spring.springbucks: DEBUG
